apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-with-secret
  name: pod-with-secret
  namespace: secrets
spec:
  containers:
  - image: httpd
    name: pod-with-secret
    resources: {}
    volumeMounts:
    - name: very-secret-information
      mountPath: /etc/secretInformation
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: very-secret-information
    secret:
      secretName: very-secret-information
status: {}
