apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-partial-secret
  name: pod-partial-secret
  namespace: secrets
spec:
  containers:
  - image: httpd
    name: pod-partial-secret
    resources: {}
    volumeMounts:
    - name: user-secret
      mountPath: /etc/username-secret-value
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: user-secret
    secret:
      secretName: very-secret-information
      items: 
      - key: user
        path: userpathvalue # required for items, will create a folder and file with "mountPath" + this "path"
status: {}
