apiVersion: v1
kind: Pod
metadata:
  labels:
    run: print-env-from-secret
  name: print-env-from-secret
  namespace: pod-env
spec:
  containers:
  - command:
    - printenv
    - FROM_SECRET
    env:
    - name: FROM_SECRET
      valueFrom:
        secretKeyRef:
          name: env-secret
          key: valueToEnv    
    image: busybox
    name: print-env-from-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}



