apiVersion: v1
kind: Pod
metadata:
  labels:
    run: httpd-cm-test
  name: httpd-cm-test
  namespace: config-map-test
spec:
  containers:
  - image: httpd
    name: httpd-cm-test
    resources: {}
    env:
    - name: LOG
      valueFrom:
        configMapKeyRef:
          name: env-configs
          key: LOG_LEVEL
    - name: ENVIROMENT
      valueFrom:
        configMapKeyRef:
          name: env-configs
          key: ENV
    command:
    - sh
    - -c
    - printenv LOG ENVIROMENT
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
