---
apiVersion: v1
kind: Namespace
metadata:
  name: node-affinity
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pod-on-worker2
  name: pod-on-worker2
  namespace: node-affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-on-worker2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pod-on-worker2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname 
                operator: In
                values: 
                - worker-02
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
...
