apiVersion: v1
kind: Pod
metadata:
  labels:
    run: data-from-container
  name: data-from-container
  namespace: container-data-from-pod
spec:
  containers:
  - name: container-one
    image: busybox
    resources: {}
  - name: container-two
    image: httpd
    command: ["sh","-c","printenv CONTAINER1_CPU_LIMIT SELFCONTAINER_CPU_LIMIT"]
    env:
    - name: CONTAINER1_CPU_LIMIT
      valueFrom:
       resourceFieldRef:
         containerName: container-one
         resource: limits.cpu
    - name: SELFCONTAINER_CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: container-two
          resource: limits.cpu
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
